import PropertyCard from "./property-card";

const PropertiesGrid = () => {
  return (
    <div className="self-stretch flex flex-row flex-wrap items-start justify-center text-left text-[14.51px] text-gray-700 font-body-regular-600">
      <div className="flex-1 flex flex-row flex-wrap items-start justify-center gap-[8px]">
        <PropertyCard
          imageDimensions="/unsplashrlwe8f8anoc@2x.png"
          imageDimensionIds="/car.svg"
          imageDimensionIds2="/bathtub.svg"
          imageDimensionValues="/arrowsout.svg"
          imageDimensionValues2="/ellipse-1@2x.png"
          imageDimensionPairs="/sharenetwork.svg"
          imageDimensionPairIds="/heart.svg"
          imageDimensionPairValues="/plus.svg"
        />
        <PropertyCard
          imageDimensions="/unsplashrlwe8f8anoc1@2x.png"
          imageDimensionIds="/car1.svg"
          imageDimensionIds2="/bathtub1.svg"
          imageDimensionValues="/arrowsout.svg"
          imageDimensionValues2="/ellipse-1@2x.png"
          imageDimensionPairs="/sharenetwork1.svg"
          imageDimensionPairIds="/heart1.svg"
          imageDimensionPairValues="/plus1.svg"
          propWidth="350px"
          propMinWidth="unset"
          propMaxWidth="unset"
        />
        <PropertyCard
          imageDimensions="/unsplashrlwe8f8anoc2@2x.png"
          imageDimensionIds="/car2.svg"
          imageDimensionIds2="/bathtub2.svg"
          imageDimensionValues="/arrowsout.svg"
          imageDimensionValues2="/ellipse-1@2x.png"
          imageDimensionPairs="/sharenetwork.svg"
          imageDimensionPairIds="/heart.svg"
          imageDimensionPairValues="/plus.svg"
          propWidth="350px"
          propMinWidth="unset"
          propMaxWidth="unset"
        />
        <PropertyCard
          imageDimensions="/unsplashrlwe8f8anoc3@2x.png"
          imageDimensionIds="/car1.svg"
          imageDimensionIds2="/bathtub1.svg"
          imageDimensionValues="/arrowsout.svg"
          imageDimensionValues2="/ellipse-1@2x.png"
          imageDimensionPairs="/sharenetwork2.svg"
          imageDimensionPairIds="/heart1.svg"
          imageDimensionPairValues="/plus2.svg"
          propWidth="350px"
          propMinWidth="unset"
          propMaxWidth="unset"
        />
        <PropertyCard
          imageDimensions="/unsplashrlwe8f8anoc@2x.png"
          imageDimensionIds="/car.svg"
          imageDimensionIds2="/bathtub.svg"
          imageDimensionValues="/arrowsout.svg"
          imageDimensionValues2="/ellipse-1@2x.png"
          imageDimensionPairs="/sharenetwork2.svg"
          imageDimensionPairIds="/heart2.svg"
          imageDimensionPairValues="/plus3.svg"
          propWidth="350px"
          propMinWidth="unset"
          propMaxWidth="unset"
        />
        <PropertyCard
          imageDimensions="/unsplashrlwe8f8anoc4@2x.png"
          imageDimensionIds="/car3.svg"
          imageDimensionIds2="/bathtub3.svg"
          imageDimensionValues="/arrowsout1.svg"
          imageDimensionValues2="/ellipse-11@2x.png"
          imageDimensionPairs="/sharenetwork3.svg"
          imageDimensionPairIds="/heart3.svg"
          imageDimensionPairValues="/plus4.svg"
          propWidth="350px"
          propMinWidth="unset"
          propMaxWidth="unset"
        />
        <PropertyCard
          imageDimensions="/unsplashrlwe8f8anoc5@2x.png"
          imageDimensionIds="/car4.svg"
          imageDimensionIds2="/bathtub4.svg"
          imageDimensionValues="/arrowsout1.svg"
          imageDimensionValues2="/ellipse-11@2x.png"
          imageDimensionPairs="/sharenetwork4.svg"
          imageDimensionPairIds="/heart4.svg"
          imageDimensionPairValues="/plus5.svg"
          propWidth="350px"
          propMinWidth="unset"
          propMaxWidth="unset"
        />
        <PropertyCard
          imageDimensions="/unsplashrlwe8f8anoc6@2x.png"
          imageDimensionIds="/car3.svg"
          imageDimensionIds2="/bathtub3.svg"
          imageDimensionValues="/arrowsout1.svg"
          imageDimensionValues2="/ellipse-11@2x.png"
          imageDimensionPairs="/sharenetwork5.svg"
          imageDimensionPairIds="/heart3.svg"
          imageDimensionPairValues="/plus6.svg"
          propWidth="350px"
          propMinWidth="unset"
          propMaxWidth="unset"
        />
      </div>
    </div>
  );
};

export default PropertiesGrid;
